version: '3.7'
services:
    app:
        container_name: training_ds
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        tty: true
        depends_on:
            - db
        volumes:
            - .:/code
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - ":9000"
        networks:
            training:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - app
        volumes:
            - ./public:/code/public
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'
        environment:
            - TZ=${APP_TIMEZONE}
        links:
            - app
        networks:
            training:
    db:
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
        container_name: mysql
        ports:
            - '3306:3306'
        volumes:
            - db-store:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            training:
networks:
    training:
        driver: bridge
volumes:
    db-store:
